service: twitterpublisherlambda

frameworkVersion: '2'

custom:
  topicArn: 'arn:aws:sns:us-east-2:310109826654:ExchangeRateSNSTopicDev'
  ssmArn: 'arn:aws:secretsmanager:us-east-2:310109826654:secret:exchange-rate-twitter-edGqY7'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-2
  environment:
    ssmArn: ${self:custom.ssmArn}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ssm:GetParameters
        - ssm:GetParameter
        - ssm:GetParametersByPath
        - secretsmanager:GetSecretValue 
      Resource:
        - ${self:custom.ssmArn}

functions:
  publishToTwitter:
    handler: handler.publishToTwitter
    environment:
      NODE_PATH: './:/opt/node_modules'
    layers:
      - arn:aws:lambda:us-east-2:310109826654:layer:ExchangeRateLayer:1
    events:
      - sns: ${self:custom.topicArn}
#    